<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit8c7bbc83813f69fe37a4bdeecc18b4f2
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'Wilder\\Autoload\\' => 16,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Wilder\\Autoload\\' => 
        array (
            0 => __DIR__ . '/../..' . '/App',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit8c7bbc83813f69fe37a4bdeecc18b4f2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit8c7bbc83813f69fe37a4bdeecc18b4f2::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit8c7bbc83813f69fe37a4bdeecc18b4f2::$classMap;

        }, null, ClassLoader::class);
    }
}
